/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#1F3C88",
        "primary-light": "#4A90E2",
        "primary-container": "#EAF4FF",
        "on-primary": "#ffffff",
        "on-primary-container": "#1F3C88",
        "primary-fixed": "#dbe8ff",
        "accent": "#3CCFCF",
        "accent-light": "#e0f9f9",
        "secondary": "#F5A623",
        "secondary-container": "#FFF3E0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#7a4f00",
        "tertiary": "#7C3AED",
        "tertiary-container": "#F3E8FF",
        "error": "#EF4444",
        "error-container": "#FEE2E2",
        "on-error": "#ffffff",
        "success": "#10B981",
        "success-container": "#D1FAE5",
        "background": "#EAF4FF",
        "on-background": "#0F172A",
        "surface": "#F0F7FF",
        "surface-dim": "#d0daf5",
        "surface-bright": "#f8fbff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f9ff",
        "surface-container": "#edf4fe",
        "surface-container-high": "#e3edfa",
        "surface-container-highest": "#d8e6f8",
        "surface-variant": "#e3edfa",
        "surface-tint": "#4A90E2",
        "on-surface": "#0F172A",
        "on-surface-variant": "#475569",
        "inverse-surface": "#1E293B",
        "inverse-on-surface": "#F1F5F9",
        "outline": "#94A3B8",
        "outline-variant": "#CBD5E1",
        "card": "rgba(255, 255, 255, 0.85)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        unit: "4px",
        gutter: "16px",
        "safe-margin": "20px",
      },
      fontFamily: {
        display: ["Sora", "Inter", "system-ui", "sans-serif"],
        heading: ["Sora", "Inter", "system-ui", "sans-serif"],
        body: ["Inter", "Noto Sans Devanagari", "system-ui", "sans-serif"],
        hindi: ["Noto Sans Devanagari", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["3rem", { lineHeight: "1.1", fontWeight: "800" }],
        "display-lg": ["2.25rem", { lineHeight: "1.15", fontWeight: "700" }],
        "display": ["1.875rem", { lineHeight: "1.2", fontWeight: "700" }],
        "headline": ["1.5rem", { lineHeight: "1.3", fontWeight: "600" }],
        "title": ["1.25rem", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body": ["1rem", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        "caption": ["0.75rem", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "overline": ["0.6875rem", { lineHeight: "1", letterSpacing: "0.06em", fontWeight: "600" }],
      },
      boxShadow: {
        "card": "0 1px 3px rgba(0,0,0,0.04), 0 4px 24px rgba(74,144,226,0.06)",
        "card-hover": "0 4px 32px rgba(74,144,226,0.12)",
        "glow": "0 0 40px rgba(74,144,226,0.15)",
        "glow-accent": "0 0 40px rgba(60,207,207,0.2)",
        "nav": "0 -1px 20px rgba(0,0,0,0.04)",
        "float": "0 8px 40px rgba(31,60,136,0.1)",
        "inner": "inset 0 2px 6px rgba(0,0,0,0.04)",
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "float-slow": "float 8s ease-in-out infinite",
        "pulse-soft": "pulse-soft 3s ease-in-out infinite",
        "slide-up": "slide-up 0.5s ease-out",
        "glow": "glow 2s ease-in-out infinite alternate",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        glow: {
          "0%": { boxShadow: "0 0 20px rgba(74,144,226,0.1)" },
          "100%": { boxShadow: "0 0 40px rgba(74,144,226,0.25)" },
        },
      },
    },
  },
  plugins: [],
};
