/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#15157d",
        "primary-container": "#2e3192",
        "on-primary": "#ffffff",
        "on-primary-container": "#9da1ff",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#04006d",
        "on-primary-fixed-variant": "#373a9b",
        "inverse-primary": "#c0c1ff",
        "secondary": "#964900",
        "secondary-container": "#ff8928",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#642f00",
        "secondary-fixed": "#ffdcc6",
        "secondary-fixed-dim": "#ffb786",
        "on-secondary-fixed": "#311300",
        "on-secondary-fixed-variant": "#723600",
        "tertiary": "#491a00",
        "tertiary-container": "#6c2a00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f19160",
        "tertiary-fixed": "#ffdbcb",
        "tertiary-fixed-dim": "#ffb692",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-fixed-variant": "#773207",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#fcf8ff",
        "on-background": "#1b1b21",
        "surface": "#fcf8ff",
        "surface-dim": "#dbd9e1",
        "surface-bright": "#fcf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2fb",
        "surface-container": "#f0ecf5",
        "surface-container-high": "#eae7f0",
        "surface-container-highest": "#e4e1ea",
        "surface-variant": "#e4e1ea",
        "surface-tint": "#4f54b4",
        "on-surface": "#1b1b21",
        "on-surface-variant": "#464652",
        "inverse-surface": "#303036",
        "inverse-on-surface": "#f2eff8",
        "outline": "#777683",
        "outline-variant": "#c7c5d4",
        "sage": "#7DAA92",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        unit: "4px",
        gutter: "16px",
        "safe-margin": "20px",
      },
      fontFamily: {
        "h1-display": ["Geist", "system-ui", "sans-serif"],
        "h2-headline": ["Geist", "system-ui", "sans-serif"],
        "h3-title": ["Geist", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "h1-display": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "h2-headline": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "h3-title": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        ambient: "0 4px 20px rgba(0,0,0,0.04)",
        "ambient-sm": "0 2px 10px rgba(0,0,0,0.02)",
        "nav": "0 -4px 20px rgba(0,0,0,0.04)",
      },
    },
  },
  plugins: [],
};
