import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { transactions, monthlyIncome } from '../data/demoData';
import jsPDF from 'jspdf';

const fadeUp = { hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0 } };
const iconMap = { 'Terracotta': 'inventory_2', 'Silk': 'checkroom', 'Saree': 'checkroom', 'Bamboo': 'chair', 'Wooden': 'inventory_2', 'Cotton': 'checkroom', 'Banarasi': 'checkroom' };
const getIcon = (name) => { for (const key in iconMap) { if (name.includes(key)) return iconMap[key]; } return 'inventory_2'; };

function generatePDF() {
  const doc = new jsPDF();
  doc.setFont('helvetica', 'bold'); doc.setFontSize(18); doc.setTextColor(21, 21, 125);
  doc.text('ShilpMitra - Trade Record Certificate', 20, 20);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(70, 70, 82);
  doc.text('Auto-generated from verified trade data', 20, 28);
  doc.setDrawColor(199, 197, 212); doc.line(20, 32, 190, 32);
  doc.setFontSize(12); doc.setTextColor(27, 27, 33);
  doc.text('Artisan: Raju Kumar', 20, 42); doc.text('Craft: Handloom | Location: Varanasi, UP', 20, 50);
  doc.text(`Period: Oct - Dec 2024`, 20, 58); doc.text(`Total Income: Rs ${transactions.reduce((s, t) => s + t.amount, 0).toLocaleString()}`, 20, 66);
  doc.line(20, 72, 190, 72);
  let y = 82;
  doc.setFont('helvetica', 'bold'); doc.setFontSize(10);
  ['Date', 'Product', 'Amount', 'UPI Ref'].forEach((h, i) => doc.text(h, [20, 55, 120, 150][i], y));
  y += 8; doc.setFont('helvetica', 'normal');
  transactions.forEach((tx) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(new Date(tx.date).toLocaleDateString('en-IN'), 20, y);
    doc.text(tx.product.substring(0, 25), 55, y);
    doc.text(`Rs ${tx.amount.toLocaleString()}`, 120, y);
    doc.text(tx.upiRef.substring(0, 15), 150, y);
    y += 7;
  });
  y += 10; doc.setFont('helvetica', 'italic'); doc.setFontSize(8); doc.setTextColor(119, 118, 131);
  doc.text('This document is auto-generated by ShilpMitra from verified app data and UPI records.', 20, y);
  doc.save('ShilpMitra_TradeRecord.pdf');
}

export default function TradeLedger() {
  const navigate = useNavigate();
  const totalIncome = monthlyIncome.reduce((s, m) => s + m.amount, 0);
  const maxIncome = Math.max(...monthlyIncome.map((m) => m.amount));

  return (
    <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: 0.06 } } }} className="page-container space-y-lg">
      <motion.section variants={fadeUp} className="flex flex-col gap-sm">
        <h2 className="font-h1-display text-h1-display text-on-surface">व्यापार लेज़र</h2>
        <p className="font-body-md text-body-md text-on-surface-variant">Trade Ledger & Analytics</p>
      </motion.section>

      {/* Monthly Summary */}
      <motion.section variants={fadeUp} className="rounded-xl p-md flex flex-col gap-md relative overflow-hidden gradient-hero text-on-primary">
        <div className="absolute -right-10 -top-10 opacity-20 pointer-events-none">
          <span className="material-symbols-outlined filled" style={{ fontSize: '150px' }}>account_balance_wallet</span>
        </div>
        <div className="flex justify-between items-start z-10">
          <div className="flex flex-col gap-xs">
            <span className="font-label-caps text-label-caps text-on-primary/80 uppercase">Monthly Income</span>
            <span className="font-h1-display text-h1-display">₹{monthlyIncome[2].amount.toLocaleString()}</span>
          </div>
          <div className="bg-on-primary/20 backdrop-blur-sm rounded-lg px-sm py-xs flex flex-col items-center">
            <span className="font-h2-headline text-h2-headline">{transactions.filter(t => t.verified).length}</span>
            <span className="font-label-caps text-label-caps text-on-primary/80">Verified</span>
          </div>
        </div>
        <button onClick={generatePDF} className="z-10 mt-sm w-full bg-on-primary text-primary font-body-md text-body-md font-bold py-sm px-md rounded-full flex items-center justify-center gap-sm hover:bg-surface-container-low transition-colors shadow-sm min-h-[48px]">
          <span className="material-symbols-outlined">picture_as_pdf</span> Download Bank-Ready Proof
        </button>
      </motion.section>

      {/* Income Chart */}
      <motion.section variants={fadeUp} className="card p-md space-y-md bg-surface-container-lowest">
        <div className="flex justify-between items-center">
          <h3 className="section-title">Income Trends</h3>
          <span className="font-label-caps text-label-caps text-on-surface-variant bg-surface-container-high px-sm py-xs rounded-full">Last 3 Months</span>
        </div>
        <div className="flex items-end justify-between h-[120px] pt-sm gap-sm">
          {monthlyIncome.map((m, i) => (
            <div key={m.month} className="flex flex-col items-center gap-xs flex-1">
              <div className="w-full rounded-t-lg relative" style={{ height: `${(m.amount / maxIncome) * 100}%` }}>
                <div className={`w-full h-full rounded-t-lg ${i === monthlyIncome.length - 1 ? 'bg-primary' : i === 1 ? 'bg-primary-container' : 'bg-secondary-container'}`} />
              </div>
              <span className={`font-label-caps text-label-caps ${i === monthlyIncome.length - 1 ? 'text-on-surface font-bold' : 'text-on-surface-variant'}`}>{m.month}</span>
            </div>
          ))}
        </div>
      </motion.section>

      {/* Transaction List */}
      <motion.section variants={fadeUp} className="space-y-md">
        <div className="flex justify-between items-center">
          <h3 className="section-title">Recent Transactions</h3>
          <button className="text-primary font-label-caps text-label-caps uppercase hover:underline">View All</button>
        </div>
        <div className="flex flex-col gap-sm">
          {transactions.slice(0, 5).map((tx) => (
            <div key={tx.id} className="card p-md flex items-center justify-between bg-surface-container-lowest">
              <div className="flex items-center gap-md">
                <div className="w-12 h-12 rounded-full bg-surface-container-high flex items-center justify-center text-primary">
                  <span className="material-symbols-outlined filled">{getIcon(tx.product)}</span>
                </div>
                <div className="flex flex-col">
                  <span className="font-body-md text-body-md font-bold text-on-surface">{tx.product}</span>
                  <span className="font-label-caps text-label-caps text-on-surface-variant">{new Date(tx.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} • {tx.buyerName}</span>
                  {tx.verified && (
                    <div className="flex items-center gap-xs mt-1 bg-surface-container-high w-fit px-2 py-0.5 rounded-full">
                      <span className="material-symbols-outlined text-[12px] text-secondary filled">verified</span>
                      <span className="font-label-caps text-label-caps text-secondary" style={{ fontSize: '10px' }}>Ledger Verified</span>
                    </div>
                  )}
                </div>
              </div>
              <div className="font-body-lg text-body-lg font-bold text-primary">+₹{tx.amount.toLocaleString()}</div>
            </div>
          ))}
        </div>
      </motion.section>
    </motion.div>
  );
}
