import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useTranslation } from '../hooks/useTranslation';
import { transactions, monthlyIncome } from '../data/demoData';
import jsPDF from 'jspdf';

const fadeUp = { hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0 } };

function generatePDF() {
  const doc = new jsPDF();
  doc.setFont('helvetica', 'bold'); doc.setFontSize(18); doc.setTextColor(31, 60, 136);
  doc.text('ShilpMitra - Trade Record Certificate', 20, 20);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(71, 85, 105);
  doc.text('Auto-generated from verified trade data • AI Verified', 20, 28);
  doc.setDrawColor(203, 213, 225); doc.line(20, 32, 190, 32);
  doc.setFontSize(12); doc.setTextColor(15, 23, 42);
  doc.text('Artisan: Raju Kumar', 20, 42); doc.text('Craft: Pottery | Location: Khurja, UP', 20, 50);
  doc.text(`Period: Oct - Dec 2024`, 20, 58); doc.text(`Total Income: Rs ${transactions.reduce((s, t) => s + t.amount, 0).toLocaleString()}`, 20, 66);
  doc.line(20, 72, 190, 72);
  let y = 82;
  doc.setFont('helvetica', 'bold'); doc.setFontSize(10);
  ['Date', 'Product', 'Amount', 'UPI Ref'].forEach((h, i) => doc.text(h, [20, 55, 120, 150][i], y));
  y += 8; doc.setFont('helvetica', 'normal');
  transactions.forEach((tx) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(new Date(tx.date).toLocaleDateString('en-IN'), 20, y);
    doc.text(tx.product.substring(0, 25), 55, y);
    doc.text(`Rs ${tx.amount.toLocaleString()}`, 120, y);
    doc.text(tx.upiRef.substring(0, 15), 150, y);
    y += 7;
  });
  y += 10; doc.setFont('helvetica', 'italic'); doc.setFontSize(8); doc.setTextColor(148, 163, 184);
  doc.text('This document is auto-generated by ShilpMitra AI from verified app data and UPI records.', 20, y);
  doc.save('ShilpMitra_TradeRecord.pdf');
}

export default function TradeLedger() {
  const navigate = useNavigate();
  const { t, lang } = useTranslation();
  const totalIncome = monthlyIncome.reduce((s, m) => s + m.amount, 0);
  const maxIncome = Math.max(...monthlyIncome.map((m) => m.amount));

  return (
    <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: 0.06 } } }} 
      className="px-4 sm:px-6 lg:px-8 py-6 lg:py-8 max-w-4xl mx-auto">
      
      {/* Header */}
      <motion.div variants={fadeUp} className="mb-6">
        <h1 className="text-2xl font-bold text-[#1F3C88]" style={{ fontFamily: 'Sora, sans-serif' }}>
          📋 {t('fund.tradeLedger')}
        </h1>
        <p className="text-sm text-slate-500 mt-1">
          {lang === 'hi' ? 'व्यापार बही और विश्लेषण' : 'Trade Ledger & Analytics'}
        </p>
      </motion.div>

      {/* Summary Card */}
      <motion.div variants={fadeUp} className="relative overflow-hidden rounded-2xl p-6 text-white mb-5"
        style={{ background: 'linear-gradient(135deg, #1F3C88 0%, #4A90E2 60%, #3CCFCF 100%)' }}>
        <div className="absolute -right-6 -top-6 opacity-10 text-[100px]">💰</div>
        <div className="flex justify-between items-start relative z-10">
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-white/60">{t('fund.monthlyIncome')}</span>
            <div className="text-3xl font-bold mt-1" style={{ fontFamily: 'Sora, sans-serif' }}>₹{monthlyIncome[2].amount.toLocaleString()}</div>
          </div>
          <div className="bg-white/15 backdrop-blur-sm rounded-xl px-4 py-2.5 text-center">
            <div className="text-xl font-bold">{transactions.filter(t => t.verified).length}</div>
            <div className="text-[10px] text-white/60 font-medium">Verified</div>
          </div>
        </div>
        <button onClick={generatePDF} 
          className="relative z-10 mt-4 w-full bg-white text-[#1F3C88] text-sm font-bold py-3 px-4 rounded-xl flex items-center justify-center gap-2 hover:shadow-lg transition-all">
          📥 {t('fund.downloadProof')}
        </button>
      </motion.div>

      {/* Income Chart */}
      <motion.div variants={fadeUp} className="bg-white rounded-xl border border-slate-100 p-5 mb-5">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-sm font-bold text-slate-700">{t('fund.incomeTrends')}</h3>
          <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-400 font-medium">
            {lang === 'hi' ? 'पिछले 3 महीने' : 'Last 3 Months'}
          </span>
        </div>
        <div className="flex items-end justify-between h-[120px] gap-3">
          {monthlyIncome.map((m, i) => (
            <div key={m.month} className="flex flex-col items-center gap-1.5 flex-1">
              <span className="text-[11px] font-semibold text-slate-500">₹{(m.amount/1000).toFixed(0)}K</span>
              <div className="w-full rounded-t-lg relative" style={{ height: `${(m.amount / maxIncome) * 80}px` }}>
                <motion.div initial={{ height: 0 }} animate={{ height: '100%' }} transition={{ duration: 0.8, delay: i * 0.15 }}
                  className={`w-full rounded-t-lg ${i === 2 ? 'bg-gradient-to-t from-[#1F3C88] to-[#4A90E2]' : 'bg-[#EAF4FF]'}`}
                  style={{ height: '100%' }} />
              </div>
              <span className={`text-[11px] ${i === 2 ? 'font-bold text-slate-700' : 'text-slate-400'}`}>{m.month}</span>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Transactions */}
      <motion.div variants={fadeUp} className="bg-white rounded-xl border border-slate-100 overflow-hidden">
        <div className="px-4 py-3 border-b border-slate-100">
          <h3 className="text-sm font-bold text-slate-700">{t('fund.recentTransactions')}</h3>
        </div>
        <div className="divide-y divide-slate-50">
          {transactions.slice(0, 6).map((tx) => (
            <div key={tx.id} className="px-4 py-3 flex items-center justify-between hover:bg-slate-25 transition-colors">
              <div className="flex items-center gap-3 min-w-0">
                <div className="w-9 h-9 rounded-lg bg-[#EAF4FF] flex items-center justify-center text-sm shrink-0">🧾</div>
                <div className="min-w-0">
                  <p className="text-[13px] font-medium text-slate-700 truncate">{tx.product}</p>
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] text-slate-400">{new Date(tx.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} • {tx.buyerName}</span>
                    {tx.verified && (
                      <span className="text-[9px] px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-600 font-semibold">✓ Verified</span>
                    )}
                  </div>
                </div>
              </div>
              <span className="text-sm font-bold text-emerald-600 shrink-0 ml-2">+₹{tx.amount.toLocaleString()}</span>
            </div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}
