import { supabase } from '../../lib/supabase.js';
import { jsPDF } from 'jspdf';

export default async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { userId } = req.body;
    if (!userId) return res.status(400).json({ error: 'userId is required' });

    // 1. Fetch user
    const { data: user } = await supabase.from('users').select('*').eq('id', userId).single();
    if (!user) return res.status(404).json({ error: 'User not found' });

    // 2. Fetch all completed transactions
    const { data: txns } = await supabase
      .from('transactions')
      .select('*')
      .eq('seller_id', userId)
      .eq('payment_status', 'completed')
      .order('created_at', { ascending: false });

    if (!txns || txns.length === 0) {
      return res.status(400).json({ error: 'No transactions found for this user' });
    }

    const totalRevenue = txns.reduce((s, t) => s + Number(t.amount), 0);
    const months = {};
    txns.forEach(t => {
      const m = t.created_at?.substring(0, 7) || 'Unknown';
      if (!months[m]) months[m] = { count: 0, total: 0 };
      months[m].count++;
      months[m].total += Number(t.amount);
    });

    // 3. Build PDF
    const doc = new jsPDF();

    // Page 1: Summary
    doc.setFontSize(20);
    doc.setTextColor(31, 60, 136); // #1F3C88
    doc.text('ShilpMitra — Trade Record', 20, 25);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 20, 33);

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Artisan: ${user.name}`, 20, 48);
    doc.text(`Craft: ${user.craft_type || 'N/A'}`, 20, 56);
    doc.text(`Location: ${user.location || 'N/A'}`, 20, 64);
    doc.text(`UPI ID: ${user.upi_id || 'N/A'}`, 20, 72);

    doc.setDrawColor(74, 144, 226);
    doc.line(20, 80, 190, 80);

    doc.setFontSize(14);
    doc.setTextColor(31, 60, 136);
    doc.text('Summary', 20, 92);

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Total Revenue: Rs. ${totalRevenue.toLocaleString('en-IN')}`, 20, 104);
    doc.text(`Total Transactions: ${txns.length}`, 20, 112);
    doc.text(`Months Active: ${Object.keys(months).length}`, 20, 120);
    doc.text(`Avg Monthly: Rs. ${Math.round(totalRevenue / Math.max(Object.keys(months).length, 1)).toLocaleString('en-IN')}`, 20, 128);

    // Page 2: Monthly breakdown
    doc.addPage();
    doc.setFontSize(14);
    doc.setTextColor(31, 60, 136);
    doc.text('Monthly Breakdown', 20, 25);

    let y = 40;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Month', 20, y);
    doc.text('Transactions', 80, y);
    doc.text('Revenue', 140, y);
    y += 4;
    doc.line(20, y, 190, y);
    y += 8;

    doc.setTextColor(0);
    Object.entries(months)
      .sort(([a], [b]) => b.localeCompare(a))
      .forEach(([month, data]) => {
        if (y > 270) { doc.addPage(); y = 25; }
        doc.text(month, 20, y);
        doc.text(String(data.count), 80, y);
        doc.text(`Rs. ${data.total.toLocaleString('en-IN')}`, 140, y);
        y += 8;
      });

    // Transaction details
    y += 8;
    if (y > 200) { doc.addPage(); y = 25; }
    doc.setFontSize(14);
    doc.setTextColor(31, 60, 136);
    doc.text('Transaction Details', 20, y);
    y += 12;

    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text('Date', 20, y);
    doc.text('Buyer', 60, y);
    doc.text('Amount', 120, y);
    doc.text('UPI Ref', 155, y);
    y += 4;
    doc.line(20, y, 190, y);
    y += 6;

    doc.setTextColor(0);
    txns.forEach(t => {
      if (y > 275) { doc.addPage(); y = 25; }
      doc.text(new Date(t.created_at).toLocaleDateString('en-IN'), 20, y);
      doc.text((t.buyer_name || 'N/A').substring(0, 20), 60, y);
      doc.text(`Rs. ${Number(t.amount).toLocaleString('en-IN')}`, 120, y);
      doc.text((t.upi_ref || 'N/A').substring(0, 18), 155, y);
      y += 7;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('This document was auto-generated by ShilpMitra AI Platform. For official verification only.', 20, 285);

    // 4. Upload to Supabase Storage
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const fileName = `trade_record_${userId}_${Date.now()}.pdf`;

    let downloadUrl = null;
    try {
      const { error: upErr } = await supabase.storage
        .from('trade-pdfs')
        .upload(fileName, pdfBuffer, { contentType: 'application/pdf' });

      if (!upErr) {
        const { data: urlData } = supabase.storage.from('trade-pdfs').getPublicUrl(fileName);
        downloadUrl = urlData?.publicUrl;
      }
    } catch (e) {
      console.warn('[pdf] Storage upload skipped:', e.message);
    }

    // 5. Return PDF as binary
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    if (downloadUrl) res.setHeader('X-Download-Url', downloadUrl);

    return res.status(200).send(pdfBuffer);
  } catch (e) {
    console.error('[pdf/trade-record]', e);
    return res.status(500).json({ error: 'Internal server error', detail: e.message });
  }
}
